version: "3.8"
services:
  frontend:
    container_name: "frontend-webapp"
    build:
      context: "."
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./jsconfig.json:/app/jsconfig.json
      - ./next.config.mjs:/app/next.config.mjs
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js

networks:
  traveling:
    external: True
