version: "3.8"
services:
  frontend:
    container_name: "frontend-webapp"
    image: tripsync/frontend:latest
    build:
      context: "."
    command: ["npm", "run", "dev"]
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./jsconfig.json:/app/jsconfig.json
      - ./next.config.mjs:/app/next.config.mjs
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.entrypoints=web"
    networks:
      - "traveling"

  api:
    container_name: "site-api"
    image: tripsync/backend:latest
    environment:
      MONGO_USERNAME: pfpreader
      MONGO_PASSWORD: pressxtodoubt
    build:
      context: "../site-api"
    volumes:
      - ../site-api/src/site_api:/project/site_api
    ports:
      - "8000:8000"
    networks:
      - "traveling"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api.entrypoints=web"

  edgedb:
    container_name: "edgedb"
    image: tripsync/database:latest
    build:
      context: "../edgedb"
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_ADMIN_UI: enabled
      EDGEDB_SERVER_PASSWORD: edgedb
    ports:
      - 5656:5656
    networks:
      - "traveling"

  tripsync-traefik:
    image: traefik:v2.5
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traveling

  mongo:
    image: mongo
    container_name: tripsync-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: pfpreader
      MONGO_INITDB_ROOT_PASSWORD: pressxtodoubt
    networks:
      - traveling

networks:
  traveling:
    external: True
